### ISSUE TITLE
Slow response to updated CRAN builds

### ISSUE THREAD

**Issue by wlandau-lilly** [krlmlr/r-appveyor#103]
[This check](https://ci.appveyor.com/project/wlandau-lilly/drake/build/1.0.1032#L225) originally failed because Appveyor could not get the R-release Windows build of `listenv` from CRAN.

```
  There are binary versions available (and will be installed) but the
  source versions are later:
        binary source
listenv  0.6.0  0.7.0
tibble   1.4.1  1.4.2
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/listenv_0.6.0.zip
```

At the time, `listenv` 0.7.0 was already built for R-release.

![listenv](https://user-images.githubusercontent.com/22958003/35348168-3a1d2692-0105-11e8-9775-0758bb715c5c.png)

In my experience, this is not the first time Appveyor/r-appeyor was slow to react.

**Comment by wlandau-lilly** [comment]
An easy workaround might be to tell Appveyor to install packages from the source when it thinks the binaries lag behind. How do I do that?

**Comment by krlmlr** [comment]
The CRAN mirrors might lag a bit, AppVeyor doesn't do any caching itself. Set the `CRAN` env var to the main website to eliminate these lags.

Installing from source might needs Rtools, please check the `USE_RTOOLS` and `PKGTYPE` environment variables in the README. This also might mean that *all* packages are installed from source.

**Comment by wlandau-lilly** [comment]
Thanks, Kirill. So I could try some of these options?

```
environment:
  global:
    CRAN: https://ftp.ussg.iu.edu/CRAN/ # Pick a CRAN mirror that updates more quickly.
    USE_RTOOLS: true                    # For building packages with low-level code from the source.
    PKG_TYPE: "source"                  # install.packages(..., type = "source")
```
