### ISSUE TITLE
Bioconductor integration now requires R 3.6

### ISSUE THREAD

**Issue by mjsteinbaugh** [krlmlr/r-appveyor#144]
Bioconductor checks are breaking again because the BioC 3.9 devel release is now pinned to R 3.6, which isn't available on the AppVeyor image. This error now gets returned for any build:

```
Error: Bioconductor version '3.9' requires R version '3.6'; see
  https://bioconductor.org/install
```

@LiNk-NY

**Comment by LiNk-NY** [comment]
R `3.6.0` is R-devel:

```
  matrix:
    - R_VERSION: devel
      R_ARCH: x64
      GCC_PATH: mingw_64
```
