### ISSUE TITLE
appveyor failed for devel R4.0.0 with package remotes fail

### ISSUE THREAD

**Issue by Fredo-XVII** [krlmlr/r-appveyor#176]
Hello,

I have tried just about every iteration of choices on the appveyor.yml to try to fix the error below.  Any help would be grateful.  Appveyor does pass for the current version of R, just not the devel.  Travis is also building. 

Thank you

My Repo: `https://github.com/Fredo-XVII/R.COVID.19`

Error:
```
+ COMMAND=install_deps
+ echo 'Running command: install_deps'
Running command: install_deps
+ shift
+ case $COMMAND in
+ InstallDeps
+ EnsureRemotes
+ Rscript -e 'if (!("remotes" %in% rownames(installed.packages()))) q(status=1)'
+ Rscript -e 'if (!("remotes" %in% rownames(installed.packages()))) q(status=1)'
+ echo 'Installing dependencies'
Installing dependencies
+ Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"), download.file.method = "auto"); remotes::install_deps(dependencies = TRUE, type="both")'
Error: package 'remotes' was installed before R 4.0.0: please re-install it
Execution halted
Command exited with code 1
7z a failure.zip *.Rcheck\*
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
```

My Appveyor.yml file:
```
# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

#platform: x64

environment:
  #R_ARCH: x64
  NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  #USE_RTOOLS: true
  #R_REMOTES_STANDALONE: true
  R_VERSION: devel
  PKGTYPE: both
  #R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

# My Adds

```
