### ISSUE TITLE
How to set appveyor for an R package in a subdirectory

### ISSUE THREAD

**Issue by hetong007** [krlmlr/r-appveyor#34]
Hello,

I am considering to set up r-appveyor for [xgboost](https://github.com/dmlc/xgboost), but now the R package is under a subdirectory `R-package`. We have a `make Rpack` command to move files in a directory for travis, but it might not work properly on Windows. 

Is there any official/convenient solution for this type of repository? Thanks a lot!

**Comment by krlmlr** [comment]
I have no experience with this kind of setup. Have you tried `make`? It could work, as R-tools should be available by default.

Another option would be to [change the working directory](http://help.appveyor.com/discussions/problems/103-change-directory) before starting the tests.

**Comment by gaborcsardi** [comment]
You can look at this example on how to run (old) r-travis from a subdir: https://github.com/craigcitro/r-travis/blob/master/.travis.yml#L22-L25

r-appveyor uses the same script, so it might work the same way.

**Comment by hofnerb** [comment]
For me the solution of @gaborcsardi didn't work directly. However I can use something similar:

```
environment:
  matrix:
  - TEST_DIR: patch
  - TEST_DIR: pkg

before_build:
  - cp ..\travis-tool.sh .\travis-tool.sh
  - cp travis-tool.sh.cmd %TEST_DIR%\travis-tool.sh.cmd
  - cd %TEST_DIR%
  - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
```

You can also ignore the `environment` settings and replace `%TEST_DIR%` with your directory, i.e., `R-package`. The important steps (for me) were to copy the scripts to the next higher level.
