### ISSUE TITLE
gcc not found with Rtools installed?

### ISSUE THREAD

**Issue by rdiaz02** [krlmlr/r-appveyor#61]
I am getting a `d:/Compiler/gcc-4.9.3/mingw_32/bin/gcc: not found` but I think I do have Rtools properly installed (the log says so: https://ci.appveyor.com/project/rdiaz02/oncosimul/build/1.0.17).

So I guess I am doing something rather silly, but I can't see what (I find it interesting that it is looking for gcc under 'd:\', when tools were installed under 'c:\', but maybe that is OK).

My appveyor.yml is as follows (I am dealing with a package in a subdirectory):
```
## https://github.com/krlmlr/r-appveyor/issues/34
## http://stackoverflow.com/questions/33411765/check-multiple-subdirectories-using-appveyor

environment:
  TEST_DIR: OncoSimulR
  R_VERSION: devel
  USE_RTOOLS: true


before_build:
   - cp ../travis-tool.sh travis-tool.sh
   - cp travis-tool.sh.cmd %TEST_DIR%\travis-tool.sh.cmd
   - cd %TEST_DIR%
   - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"


build_script:
  - travis-tool.sh install_bioc_deps

test_script:
  - travis-tool.sh run_tests
```
